feature/AP5-94
dmstringer/rigex-project pull request #65
Opened 2021-02-18 21:12 UTC by jeremy-roussel

Vital Resources page setup and Header component

2021-02-18 21:25 UTC, BarretteBanner approved these changes

2021-02-19 04:26 UTC, BarretteBanner commented on rigex-front-end/src/components/vital-resources/Header.js
> +import building from '../../assets/building2.jpeg'
Let's use faker for all our images. You should not need any asset files for this sprint

2021-02-19 04:27 UTC, BarretteBanner requested changes
use faker

2021-02-19 21:19 UTC, mmevans approved these changes

2021-02-19 22:16 UTC, BarretteBanner approved these changes

2021-02-19 22:17 UTC, merged